// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package musesproject.eu;

import musesproject.eu.EmployeeBean;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmployeeBean_Roo_Configurable {
    
    declare @type: EmployeeBean: @Configurable;
    
}
