// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package musesproject.eu;

import java.io.Serializable;

import musesproject.eu.EmployeeBean;

privileged aspect EmployeeBean_Roo_Serializable {
    
    declare parents: EmployeeBean implements Serializable;
    
    private static final long EmployeeBean.serialVersionUID = 1L;
    
}
