// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unige.converter;

import ch.unige.converter.UserProfileConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserProfileConverter_Roo_Configurable {
    
    declare @type: UserProfileConverter: @Configurable;
    
}
